# Generated by Django 4.2.29 on 2026-03-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_carpool_ride_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='departure_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_seat',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
