"""
Django settings for smart_rental project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from typing import List, Optional

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(dotenv_path: Path) -> None:
    if not dotenv_path.exists():
        return

    for raw_line in dotenv_path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def _env_list(name: str, default: Optional[List[str]] = None) -> List[str]:
    value = os.getenv(name, '')
    items = [item.strip() for item in value.split(',') if item.strip()]
    if items:
        return items
    return default or []


def _env_int(name: str, default: int) -> int:
    value = os.getenv(name)
    if value is None:
        return default
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


_load_dotenv(BASE_DIR / '.env')

# Toggle S3 media storage with env var. Keep local storage as fallback.
USE_S3 = _env_bool('USE_S3', False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-c#611#r7dhy80h1zny4$rz$5su_ertq(9$lzyp4wyj@(8a250r')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = _env_list(
    'DJANGO_ALLOWED_HOSTS',
    default=['localhost', '127.0.0.1'] if DEBUG else [],
)

# Load balancer / reverse proxy compatibility.
USE_X_FORWARDED_HOST = _env_bool('USE_X_FORWARDED_HOST', True)
if _env_bool('USE_SECURE_PROXY_SSL_HEADER', True):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'corsheaders',

    # Local apps
    'users',
    'properties',
    'bookings',
    'reviews',
]

if USE_S3:
    INSTALLED_APPS.append('storages')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]


def _host_to_origins(host: str) -> List[str]:
    clean = host.strip()
    if not clean or clean == '*':
        return []
    if clean.startswith('http://') or clean.startswith('https://'):
        return [clean]
    return [f'http://{clean}', f'https://{clean}']


_derived_origins: List[str] = []
for _host in ALLOWED_HOSTS:
    _derived_origins.extend(_host_to_origins(_host))

# De-duplicate while preserving order.
_derived_origins = list(dict.fromkeys(_derived_origins))

CORS_ALLOW_ALL_ORIGINS = _env_bool('CORS_ALLOW_ALL_ORIGINS', DEBUG)
CORS_ALLOW_CREDENTIALS = _env_bool('CORS_ALLOW_CREDENTIALS', True)  # required for cookie (session) auth from frontend
CORS_ALLOWED_ORIGINS = _env_list('CORS_ALLOWED_ORIGINS', default=_derived_origins)

# Allow CSRF-protected POSTs from configured origins.
CSRF_TRUSTED_ORIGINS = _env_list(
    'CSRF_TRUSTED_ORIGINS',
    default=[
        'http://localhost:3000',
        'http://127.0.0.1:3000',
    ] if DEBUG else _derived_origins,
)

ROOT_URLCONF = 'smart_rental.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smart_rental.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#
# Default: PostgreSQL, configured via environment variables so we can
# point to a local Postgres instance in development and later to
# Amazon RDS just by changing env vars (no code changes needed).

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'smart_rental'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'CONN_MAX_AGE': _env_int('DB_CONN_MAX_AGE', 60),
        'OPTIONS': {
            # Fail fast when DB is unreachable so Nginx does not surface long 504 timeouts.
            'connect_timeout': _env_int('DB_CONNECT_TIMEOUT', 5),
        },
    }
}

AUTH_USER_MODEL = 'users.CustomUser'

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media uploads (e.g., property images)
if USE_S3:
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', '')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', '')
    AWS_SESSION_TOKEN = os.getenv('AWS_SESSION_TOKEN', '')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', '')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', '')
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_FILE_OVERWRITE = False

    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }

    custom_domain = os.getenv('AWS_S3_CUSTOM_DOMAIN', '').strip()
    if custom_domain:
        MEDIA_URL = f"https://{custom_domain}/"
    elif AWS_STORAGE_BUCKET_NAME and AWS_S3_REGION_NAME:
        MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/"
    else:
        MEDIA_URL = '/media/'
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework — cookie (session) auth for browser clients
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # per-view override for protected endpoints
    ],
}

# CloudWatch Logging Configuration
CLOUDWATCH_ENABLED = _env_bool('CLOUDWATCH_LOGGING_ENABLED', False)
CLOUDWATCH_LOG_GROUP = os.getenv('CLOUDWATCH_LOG_GROUP', 'smart-rental-backend')
CLOUDWATCH_LOG_STREAM = os.getenv('CLOUDWATCH_LOG_STREAM', 'django-app')
AWS_REGION_NAME = os.getenv('AWS_REGION', 'us-east-1')

# Django Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'detailed': {
            'format': '[%(asctime)s] %(levelname)s [%(name)s:%(funcName)s():%(lineno)s] %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'standard'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'smart_rental': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'bookings': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'properties': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'users': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Add CloudWatch handler if enabled and watchtower is installed
if CLOUDWATCH_ENABLED:
    try:
        import watchtower
        LOGGING['handlers']['cloudwatch'] = {
            'level': 'DEBUG',
            'class': 'watchtower.CloudWatchLogHandler',
            'log_group': CLOUDWATCH_LOG_GROUP,
            'stream_name': CLOUDWATCH_LOG_STREAM,
            'region_name': AWS_REGION_NAME,
            'formatter': 'detailed',
            'boto3_client_kwargs': {'region_name': AWS_REGION_NAME},
        }
        # Add cloudwatch to all loggers
        for logger_name in LOGGING['loggers']:
            if 'cloudwatch' not in LOGGING['loggers'][logger_name]['handlers']:
                LOGGING['loggers'][logger_name]['handlers'].append('cloudwatch')
    except (ImportError, Exception) as e:
        # If watchtower not available or CloudWatch auth fails, fall back to file logging
        import warnings
        log_file = BASE_DIR / 'logs' / 'django.log'
        log_file.parent.mkdir(exist_ok=True)
        LOGGING['handlers']['file'] = {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(log_file),
            'maxBytes': 10485760,  # 10MB
            'backupCount': 5,
            'formatter': 'detailed',
        }
        # Add file handler to all loggers as fallback
        for logger_name in LOGGING['loggers']:
            if 'file' not in LOGGING['loggers'][logger_name]['handlers']:
                LOGGING['loggers'][logger_name]['handlers'].append('file')
        warnings.warn(f'CloudWatch logging failed ({e}). Falling back to file logging at {log_file}')
